const COMMON_PARTS = [
['Base y tapa','2','220 × 120 × 12 mm','Contrachapado; tapa desmontable.'],
['Paredes laterales','2','108 × 120 × 12 mm','Altura total con base y tapa: 132 mm.'],
['Eje principal','1','Ø6 × 270 mm','Varilla lisa recta; metal o madera dura.'],
['Leva circular','Por canal','Ø50 × 10 mm; excentricidad 4 mm','Corta la periferia con marquetería; taladra solo el agujero excéntrico.'],
['Patín seguidor','Por canal','36 × 40 × 8 mm','Cara inferior plana y suave.'],
['Varillas de guía','2 por canal','Ø6 × 100 mm','Pegadas al patín, libres en la tapa.'],
['Manivela y mango','1 + 1','60 × 20 × 10 mm; mango Ø8 × 35 mm','Distancia de 40 mm entre centros.'],
['Topes de eje','2','Collares para eje de Ø6 mm','Preferible desmontables para ajustar.'],
['Soportes de tapa','4','20 × 20 × 20 mm','Encolados dentro de las esquinas.'],
['Fijación de tapa','4','Tornillos de madera 3 × 25 mm','Agujeros de paso en tapa; pilotos en soportes.']
];
const TOOLS='Sierra de marquetería o de cinta para contornos; taladro de columna con mordaza para agujeros alineados; brocas acordes a ejes y tornillos; lijas 120–240, lima fina, escuadra, calibre, sargentos y destornilladores. CNC o láser son alternativas para piezas compatibles con cada máquina; no sustituyen el ajuste final. Usa protección ocular y extracción de polvo según la herramienta. Nunca taladres una pieza pequeña sosteniéndola en la mano.';
const STEPS_COMMON = [
['Dibuja el gesto antes de cortar','Recorta la figura y sus piezas móviles en cartón. Únelas con broches de papel en los pivotes previstos. Recorre a mano el gesto completo y señala el punto por donde empujará la varilla. Comprueba que el movimiento no choque con el cuerpo. Traslada al contrachapado solo la geometría que funciona. Las dimensiones de figura son envolventes orientativas, no plantillas 1:1.','sketch'],
['Construye un bastidor escuadrado','Base y tapa: 220 × 120 × 12 mm. Coloca los laterales de 108 mm de altura encima de la base, enrasados a sus extremos; queda un espacio interior de 196 mm. Antes de unir, perfora los laterales con el centro del eje a 54 mm desde su borde inferior y a 60 mm desde el frente. Para eje de 6 mm, prueba un agujero de 6,3–6,5 mm sobre descarte; debe girar sin agarrotarse. Encola y prensa base y laterales. Pega cuatro apoyos de tapa por dentro, fuera del recorrido del eje y de las levas; fija la tapa con cuatro tornillos para poder desmontarla.','frame'],
['Fabrica las levas y el eje','Traza discos de 50 mm de diámetro sobre contrachapado de 10 mm. Marca el centro geométrico y el agujero del eje a 4 mm de él. Corta con marquetería, lija la periferia y taladra únicamente ese agujero excéntrico: una sierra de copa dejaría un segundo agujero central que se solaparía con él. Cada disco necesita un cubo de fijación compatible con eje de 6 mm; usa cubos con tornillo prisionero para poder cambiar la fase, fijados al disco con tornillos pasantes según su fabricante. Encola solo si usas un eje de madera y ya verificaste la fase.','cam'],
['Prepara un seguidor por canal','Haz un patín de 36 × 40 × 8 mm por leva. Pega dos varillas de 6 mm paralelas en agujeros ciegos de 4 mm de profundidad, separados 20 mm en el sentido del fondo. Transfiere sus centros a la tapa: ambas comparten la coordenada longitudinal de su leva, y se sitúan a 50 y 70 mm del frente. Los agujeros de la tapa deben dejar deslizar las varillas sin atasco; prueba la holgura real. La pareja de guías evita que el patín rote. No pegues nada en la tapa. El propio peso debe mantener contacto con la leva.','follower'],
['Prueba el mecanismo sin personaje','Monta las levas sobre el eje en las posiciones indicadas para este proyecto. Deja los patines apoyados sobre ellas. Coloca los topes fuera de las paredes con alrededor de 1 mm de juego axial. Fija la manivela al eje mediante un cubo compatible y el mango a su extremo; el mango no debe rozar la pared. Gira despacio: con radio 25 mm y excentricidad 4 mm, el seguidor plano tiene una carrera ideal de 8 mm. El eje queda a 66 mm de la mesa; el máximo de la leva está a 95 mm, el patín a 103 mm y la cara inferior de la tapa a 120 mm. Esas holguras no incluyen cubos que sobresalgan: compruébalos por separado.','drive'],
];
const FINAL_STEPS=[
['Afina el giro y el retorno','Con la figura montada, gira una vuelta muy lentamente. Comprueba que cada seguidor permanece en contacto con su leva y que no se inclina. Si el retorno por gravedad falla, reduce fricción, aligera la pieza o añade un contrapeso pequeño fijado mecánicamente; no añadas piezas sueltas. Un agujero de paso es mayor que el eje del pivote; el agujero piloto de un tornillo para madera es distinto y debe respetar el diámetro de su núcleo. Usa arandelas y tuercas autoblocantes o fijaciones apropiadas: el pivote debe girar sin aflojarse.','tune'],
['Acaba y vuelve a comprobar','Desmonta las piezas que lo permitan, lija y aplica el acabado elegido siguiendo su etiqueta. Protege agujeros, ejes, caras de contacto y articulaciones para que el acabado no los bloquee. Tras el curado, monta y prueba diez vueltas lentas en cada sentido. Revisa tornillos y puntos de pellizco. No añadas un motor sin rediseñar protección, transmisión y límite de esfuerzo. Estos proyectos son esculturas mecánicas de sobremesa, no juguetes infantiles certificados.','finish']
];
const PROJECTS=[
{id:'perro',n:'01',name:'El perro juguetón',kind:'dog',level:'avanzado',time:'3–4 sesiones',tone:'#e9e0cf',tag:'DOS GESTOS · UN EJE',desc:'Una pata que busca la pelota y una cola que acompaña el juego.',mechanism:'Dos levas + palancas',channels:2,phase:90,action:'El cuerpo queda fijo. Una leva eleva la pata delantera y otra hace oscilar la cola, desfasada un cuarto de vuelta. La pelota permanece fija.',extra:[['Cuerpo y cabeza','1 + 1','Envolvente 150 × 95 mm; espesor 9 mm','Silueta propia; dos apoyos fijos a la tapa.'],['Pata móvil y cola','1 + 1','Pata 75 × 18 × 6 mm; cola 60 × 15 × 6 mm','Pivotes independientes; no unir rígidamente al cuerpo.'],['Pivotes','2','Pernos M3, arandelas y tuercas autoblocantes','Longitud según el apilado; sin puntas expuestas.'],['Pelota y pedestal','1 + 1','Pelota Ø25–30 mm; pedestal a ajustar','Ambos fijos, fuera del alcance extremo de la pata.']],
layout:'Coloca los canales bajo la pata y la cola. Para la prueba del bastidor usa x = 75 y 155 mm desde el extremo izquierdo, con los cubos sin tocar seguidores. Orienta la segunda leva 90° respecto a la primera. Coloca después el perro sobre apoyos fijos y desplázalo para alinear sus puntos de empuje con las varillas; no inclines las guías para compensar un mal alineamiento.',
assembly:'Sitúa un pivote en el hombro de la pata y otro en la raíz de la cola, ambos con ejes perpendiculares al plano de la silueta. Deja un pequeño brazo de palanca oculto detrás de cada pieza, solidario con ella. Apoya el empujador en ese brazo a unos 30 mm del pivote para la pata y 25 mm para la cola. Con carrera de 8 mm y brazo casi horizontal a media carrera, el gesto será moderado. No pegues el empujador a la palanca: desliza bajo ella. Ajusta la posición del pivote y la longitud de las varillas con el modelo de cartón; las dos piezas deben regresar por gravedad.',
character:'Recorta y lija las siluetas verificadas en cartón. Sujeta cuerpo y cabeza sobre dos postes rígidos unidos a la tapa; la figura no debe sostenerse sobre los seguidores. Prueba primero la pata sola, luego la cola y finalmente las dos levas. Añade la pelota cuando conozcas el arco máximo de la pata; deja 3 mm de margen para evitar golpes.',checks:['La pata no golpea la pelota ni carga peso sobre ella.','La cola vuelve sin quedarse levantada.','Los dos movimientos están desfasados; no se bloquean entre sí.']},
{id:'pajaro',n:'02',name:'El pájaro curioso',kind:'bird',level:'intermedio',time:'2–3 sesiones',tone:'#e2e7db',tag:'UN PICOTEO A CADA VUELTA',desc:'Una pequeña ave inclina la cabeza para investigar su rincón.',mechanism:'Leva + balancín',channels:1,phase:0,action:'Las patas y el cuerpo permanecen fijos. La cabeza, con el pico unido a ella, bascula sobre un pivote de cuello. No mueve las alas.',extra:[['Cuerpo fijo','1','Envolvente 90 × 65 × 9 mm','Incluye apoyos rígidos; alas decorativas.'],['Cabeza y pico','1 conjunto','Envolvente 60 × 40 × 6 mm','Pico ligero pegado a la cabeza.'],['Brazo oculto del cuello','1','30–40 × 12 × 6 mm','Solidario a la cabeza; contacto a 25 mm del pivote.'],['Pivote de cuello','1','Perno M3, arandelas, tuerca autoblocante','Agujero de paso libre en la cabeza.']],
layout:'Usa un canal centrado en x = 110 mm. La varilla empuja un brazo oculto que sobresale detrás del cuello. El cuerpo se fija a la tapa; coloca el pivote de manera que el punto de contacto del brazo quede sobre el seguidor.',
assembly:'Haz el pivote del cuello con perno y arandelas. Pega detrás de la cabeza un brazo corto que quede aproximadamente horizontal a media carrera. El seguidor empuja debajo de ese brazo, a unos 25 mm del pivote. Sitúa el brazo y el peso de la cabeza para que elevar el brazo haga bajar el pico, y para que el brazo vuelva a apoyar por gravedad. Ensaya en cartón antes de taladrar la cabeza. No busques un golpe brusco: usa un picoteo suave.',
character:'Pega las alas al cuerpo fijo y sujeta las patas a una peana rígida. Conecta únicamente la cabeza al balancín. Ajusta la longitud del empujador para conservar al menos 3 mm entre el pico y la superficie en el punto más bajo. Si se necesita más gesto, revisa las proporciones de la palanca antes de aumentar la excentricidad.',checks:['El pico se aproxima sin golpear la peana.','La cabeza vuelve libre y no roza el cuerpo.','El brazo del cuello no sale del extremo del empujador.']},
{id:'gato',n:'03',name:'El gato y la mariposa',kind:'cat',level:'intermedio',time:'2–3 sesiones',tone:'#e9e1d4',tag:'UNA PATA LLENA DE CURIOSIDAD',desc:'El gato levanta la pata hacia una mariposa posada frente a él.',mechanism:'Leva + pata articulada',channels:1,phase:0,action:'El gato eleva una pata delantera. Su cuerpo, su cola y la mariposa están fijos. La escena deja visible el mecanismo de elevación.',extra:[['Silueta fija del gato','1','Envolvente 115 × 110 × 9 mm','Cabeza y cola pueden integrarse en la silueta.'],['Pata móvil','1','65 × 18 × 6 mm','Ensaya su arco sobre cartón.'],['Pivote de hombro','1','Perno M3, arandelas y tuerca autoblocante','No apretar la madera contra el cuerpo.'],['Mariposa y poste','1 + 1','Mariposa 35 × 30 × 3 mm; poste a ajustar','Elemento estático; fuera del alcance de la pata.']],
layout:'Monta un canal en x = 110 mm. Ubica el gato para que el contacto bajo la pata esté verticalmente sobre ese canal. La mariposa irá en un poste fijo por delante del gato; su posición se decide al final.',
assembly:'Monta la pata por fuera del cuerpo con una arandela separadora. Deja su cara inferior apoyada sobre una pequeña zapata lisa del empujador, a unos 30 mm del hombro. El seguidor solo empuja: la pata vuelve por su propio peso. A mitad de carrera, mantén aproximadamente horizontal el tramo entre pivote y contacto. Si la pata queda demasiado vertical, cambia el punto de apoyo para evitar que la varilla se escape.',
character:'Recorta cabeza, orejas, cuerpo y cola con marquetería; redondea las puntas frágiles. Fija el cuerpo a dos apoyos de madera sobre la tapa. Ajusta primero el giro del hombro sin leva y luego el empuje. Pega la mariposa a su poste dejando un margen mayor que el recorrido de la pata; no tiene mecanismo propio en este modelo.',checks:['La pata gira sin llevarse el cuerpo consigo.','El apoyo permanece bajo la pata durante toda la vuelta.','La mariposa queda fuera del arco de la pata.']},
{id:'ballena',n:'04',name:'La ballena viajera',kind:'whale',level:'intermedio',time:'2–3 sesiones',tone:'#dee7e3',tag:'UNA COLA QUE DIBUJA EL MAR',desc:'Una ballena suspendida mueve su cola con un ritmo tranquilo.',mechanism:'Leva + cola basculante',channels:1,phase:0,action:'El cuerpo permanece sobre un soporte fijo y la cola oscila arriba y abajo. La ballena no se desplaza por la base.',extra:[['Cuerpo de ballena','1','Envolvente 145 × 55 × 9 mm','Soporte fijo bajo el centro del cuerpo.'],['Cola articulada','1','65 × 35 × 6 mm','Separada del cuerpo y con paso libre.'],['Pivote de cola','1','Perno M3, arandelas y tuerca autoblocante','Deja espacio entre cuerpo y aleta.'],['Brazo de cola','1','35 × 12 × 6 mm','Punto de empuje a 25 mm del pivote.']],
layout:'Coloca la leva en x = 140 mm para situarla bajo la unión de la cola. El cuerpo se apoya sobre un poste rígido independiente. Ajusta el soporte del cuerpo para que el brazo de la cola reciba el empuje vertical sin inclinar la guía.',
assembly:'Añade un brazo recto y corto solidario a la cola. Monta el pivote entre dos pequeñas orejetas fijas al cuerpo o al soporte trasero. El seguidor empuja la cara inferior del brazo a unos 25 mm del pivote. Centra el brazo cerca de la horizontal a media carrera. Mantén la masa de la aleta del lado que devuelve el brazo al contacto; compruébalo sin leva antes de fijar todo.',
character:'Corta la silueta y la cola por separado. Lija las caras enfrentadas y comprueba un margen de 2–3 mm para que no choquen al bascular. Añade una ola decorativa fija a la tapa solo después de revisar el recorrido completo. Si la cola pesa demasiado, aligérala; no intentes vencer la resistencia forzando la manivela.',checks:['El cuerpo está sostenido por un apoyo fijo.','La cola no roza el cuerpo ni las olas decorativas.','El seguidor conserva contacto durante el descenso.']},
{id:'mariposa',n:'05',name:'La mariposa del jardín',kind:'butterfly',level:'avanzado',time:'3–4 sesiones',tone:'#e7e4d2',tag:'DOS ALAS · UN MISMO PULSO',desc:'Dos alas articuladas se abren al ritmo de una sola manivela.',mechanism:'Leva + balancines gemelos',channels:1,phase:0,action:'El cuerpo permanece fijo. Un seguidor con travesaño empuja dos alas simétricas desde abajo; las alas vuelven por gravedad.',extra:[['Cuerpo fijo','1','70 × 16 × 12 mm','Sobre soporte rígido central.'],['Alas','2','Envolvente 70 × 65 × 4–6 mm cada una','Ligeras y de masas parecidas.'],['Bisagras miniatura','2','Apropiadas al espesor real','Ejes paralelos al cuerpo; fijaciones sin atravesar.'],['Travesaño móvil','1','70 × 15 × 8 mm','Dos apoyos simétricos a 25 mm del eje central.']],
layout:'Coloca el canal central en x = 110 mm. Orienta la mariposa vista de frente: el eje de cada bisagra va de delante a atrás. El travesaño móvil cruza debajo de ambas alas y no debe tocar el cuerpo fijo.',
assembly:'Une cada ala al costado del cuerpo mediante una bisagra pequeña, con el eje alineado de delante a atrás. Fija un travesaño a las dos varillas del seguidor: sus extremos tendrán dos zapatas redondeadas bajo las alas. Colócalas a distancias iguales, aproximadamente 25 mm desde cada bisagra, y ajusta la longitud del travesaño al ancho del cuerpo. Las alas descansan sobre ellas, sin pegamento. Limita el gesto a un ángulo moderado alrededor de la horizontal: ninguna debe pasar a una posición donde deje de regresar por gravedad.',
character:'Corta dos alas simétricas en madera fina. Lija juntas sus aristas para igualarlas. Fija el cuerpo a un soporte estrecho que no cruce el recorrido del travesaño. Ajusta las zapatas a la misma altura y prueba las alas antes de decorar. Para esconder el mecanismo, usa hojas decorativas con holgura suficiente, no una carcasa que bloquee el acceso.',checks:['Ambas alas arrancan juntas y vuelven sin ayuda.','Ningún ala pasa a una posición casi vertical.','El travesaño no toca el soporte central ni las bisagras.']},
{id:'tambor',n:'06',name:'El pequeño percusionista',kind:'drummer',level:'avanzado',time:'3–4 sesiones',tone:'#e6ddd1',tag:'UN GOLPE, DESPUÉS EL OTRO',desc:'Dos brazos alternan las baquetas sobre un pequeño tambor.',mechanism:'Dos levas a 180°',channels:2,phase:180,action:'El torso queda fijo y dos brazos oscilan alternadamente. Las baquetas se acercan al tambor sin golpearlo en esta versión; producir sonido requiere un ajuste adicional.',extra:[['Torso y cabeza','1 + 1','Torso 65 × 75 × 9 mm; cabeza Ø35 × 9 mm','Ambos sobre soporte fijo.'],['Brazos','2','65 × 15 × 6 mm','Un pivote en cada hombro.'],['Baquetas','2','Varilla Ø3 × 55 mm','Pegadas al extremo de cada brazo.'],['Tambor y pedestal','1 conjunto','Envolvente Ø55 × 30 mm','Fijo a la tapa; no es una membrana sonora.'],['Pivotes','2','Pernos M3, arandelas y tuercas autoblocantes','Controla que no se aflojen al girar.']],
layout:'Sitúa los canales bajo cada brazo, inicialmente x = 80 y 140 mm. Orienta las excentricidades en sentidos opuestos: 180°. Ajusta la anchura de los hombros o usa brazos de palanca ocultos para que ambos contactos queden directamente sobre sus guías.',
assembly:'Monta cada brazo en su hombro con perno, arandelas y tuerca autoblocante. El seguidor empuja un brazo oculto o la cara inferior del antebrazo a unos 30 mm del pivote. Mantén ambos contactos a distancias iguales del hombro. Fija las baquetas y deja que los brazos regresen por peso propio. Prueba cada canal solo antes de alternarlos. No amarres los dos brazos entre sí: deben moverse de forma independiente.',
character:'Fija cabeza y torso a una estructura rígida y deja libres los hombros. Coloca el tambor después de medir el punto más bajo de ambas baquetas. Deja 2–3 mm de holgura: el objetivo inicial es alternar, no percutir. Si luego quieres contacto sonoro, necesitarás revisar retorno, esfuerzo y superficie de golpeo con un prototipo específico.',checks:['Los brazos alternan, no suben al mismo tiempo.','Las baquetas no golpean ni se cruzan.','El torso no se balancea con los seguidores.']}
];
function guideSteps(p){return [...STEPS_COMMON.slice(0,4),['Coloca los canales y la fase',p.layout,'layout'],STEPS_COMMON[4],['Recorta y fija el personaje',p.character,'figure'],['Conecta las articulaciones',p.assembly,'joint'],...FINAL_STEPS]}
